<a href="https://colab.research.google.com/github/anindhOP/ai-club/blob/main/NUMPY/NumpyTutorial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# ***NUMPY IN DIFFERENT WAYS***

In [5]:
import numpy as np

**lists**

In [1]:
PythonList = [1,4,2,8]
print(PythonList)


[1, 4, 2, 8]


**NUMPY**

In [6]:
numpy_array = np.array(PythonList)
numpy_array

array([1, 4, 2, 8])

In [7]:
a = numpy_array+10
print(a)

[11 14 12 18]


In [8]:
a = np.array([1,2,7])
print(a)

[1 2 7]


In [9]:
b = a +10
print(b)

[11 12 17]


In [10]:
print(a.shape)
print(a.dtype)

(3,)
int64


In [11]:
c = np.array([(1,4,8,0),
              (4,2,6,8)])
print(c)

[[1 4 8 0]
 [4 2 6 8]]


In [12]:
d = np.array([
    [[1, 2,3],
        [4, 5, 6]],
      [[7, 8,9],
        [10, 11, 12]]
])
print(d.shape)

(2, 2, 3)


**TO PRINT 3 ROWS 3 COULMNS OF ONES**

In [18]:
x=np.ones((3,3), dtype=np.int16)
print(x)

[[1 1 1]
 [1 1 1]
 [1 1 1]]


**TO PRINT 3 TIMES OF 2 ROWS 4 COLUMNS OF ZEROES**

In [20]:
y=np.zeros((3,2,4), dtype=np.int16)
print(y)

[[[0 0 0 0]
  [0 0 0 0]]

 [[0 0 0 0]
  [0 0 0 0]]

 [[0 0 0 0]
  [0 0 0 0]]]


**RESHAPE TO 1 ELEMENT LISTS**

In [21]:
e  = np.array([(1,2,3), (4,6,8)])
print(e)
e.reshape(6,1)

[[1 2 3]
 [4 6 8]]


array([[1],
       [2],
       [3],
       [4],
       [6],
       [8]])

In [22]:
print(e)

[[1 2 3]
 [4 6 8]]


In [23]:
print('First row:', e[0])
print('Second row:', e[1])

First row: [1 2 3]
Second row: [4 6 8]


In [24]:
print('Second column:', e[:,1])

Second column: [2 6]


In [25]:
print(e[1, :2])

[4 6]


In [26]:
e.flatten()

array([1, 2, 3, 4, 6, 8])

**HORITONTAL AND VERTICAL STACK**

In [27]:
f = np.array([1,2,3])
g = np.array([4,6,8])

print('Horizontal Append:', np.hstack((f, g)))
print("Vertical append:")
print(np.vstack((f,g)))

Horizontal Append: [1 2 3 4 6 8]
Vertical append:
[[1 2 3]
 [4 6 8]]


**TO FIND A LIST OF RANDOM ELEMENTS**

In [28]:
normal_array = np.random.normal(5, 0.8, 10)
print(normal_array)

[3.60712847 4.597076   4.96709517 4.57433037 5.44031698 4.78491488
 5.80623675 5.25113013 4.06903684 5.26860121]


**FIND MIN , MAX, MEAN, MEDIAN,STD FROM A LISTS**

In [ ]:
print(np.min(normal_array))
print(np.max(normal_array))
print(np.mean(normal_array))
print(np.median(normal_array))
print(np.std(normal_array))

4.352212613229316
5.49238727930963
4.8907612207322115
4.948102144090097
0.34917526053989645


**TO PRINT ELEMENTS IN RANGE**

In [29]:
np.arange(1, 9)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [30]:
np.arange(1, 9,4)

array([1, 5])

In [ ]:
np.linspace(1.0, 10.0, num=20)

array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
        3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
        5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
        8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ])

In [31]:
np.linspace(1.0, 5.0, num=5, endpoint=False)

array([1. , 1.8, 2.6, 3.4, 4.2])

In [32]:
np.logspace(3.0, 4.0, num=4)

array([ 1000.        ,  2154.43469003,  4641.58883361, 10000.        ])

In [33]:
x = np.array([1,2,3], dtype=np.complex128)
x.itemsize

16

**TO FIND DOT PRODUCT OF MATRIX**

In [34]:
f = np.array([1,2,3])
g = np.array([4,5,6])
### 1*4+2*5+3*1
np.dot(f, g)

32

**TO FIND THE INVERSE OF MATRIX**

In [35]:
A = np.array([[6, 1, 1],
              [4, 2, 6],
              [2, 8, 4]])
  
# Calculating the inverse of the matrix
print(np.linalg.inv(A))

[[ 0.18518519 -0.01851852 -0.01851852]
 [ 0.01851852 -0.10185185  0.14814815]
 [-0.12962963  0.21296296 -0.03703704]]


**TO FIND THE MATRIX MULTIPLICATION**

In [36]:
h = [[1,2],[3,4]] 
i = [[5,6],[7,8]] 
### 1*5+2*7 = 19
np.matmul(h, i)

array([[19, 22],
       [43, 50]])

**TO FIND THE DETERMINANT OF MATRIX**

In [37]:
n_array = np.array([[50, 31], [30, 44]])
  
# Displaying the Matrix
print("Numpy Matrix is:")
print(n_array)
  
# calculating the determinant of matrix
det = np.linalg.det(n_array)
  
print("\nDeterminant of given 2X2 matrix:")
print(int(det))

Numpy Matrix is:
[[50 31]
 [30 44]]

Determinant of given 2X2 matrix:
1270


**TO FIND THE RANK OF MATRIX**

In [38]:
mx = np.array([[1,1,1],[1,2,2],[1,3,3]])

# Let's get rank of matrix 
np.linalg.matrix_rank(mx)

2

**TO FIND THE TRANSPOSE OF THE MATRIX**

In [40]:
gfg = np.matrix('[4, 2; 12, 4]')
              
# applying matrix.transpose() method
trans = gfg.transpose()
    
print(trans)

[[ 4 12]
 [ 2  4]]


**TO FIND THE TRACE OF MATRIX**

In [41]:
gfg = np.matrix('[4, 2; 12, 4]')
              
# applying matrix.trace() method
tracem = gfg.trace()
    
print(tracem)

[[8]]


**TO FIND THE EIGEN VALUES AND EIGEN VECTORS OF MATRIX**

In [42]:
example_matrix = np.array([
  [1,2,3,4],
  [5,6,7,8],
  [9,10,11,12],
  [13,14,15,16]
])
eigenvalues, eigenvectors = np.linalg.eig(example_matrix)
print(eigenvalues, eigenvectors)

[ 3.62093727e+01 -2.20937271e+00 -5.14138333e-16 -2.08943529e-15] [[-0.15115432 -0.72704996  0.01790738 -0.26832672]
 [-0.34923733 -0.28320876  0.38415354  0.71367217]
 [-0.54732033  0.16063243 -0.82202921 -0.62236419]
 [-0.74540333  0.60447363  0.41996829  0.17701873]]
